<?php

/**
 * This file is part of the Esteren project.
 *
 * (c) Pierstoval <pierstoval@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use Pierstoval\Bundle\ToolsBundle\Serializer\SerializableMediaUrl;
use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;
use JMS\Serializer\Annotation as Serializer;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author Pierstoval <pierstoval@gmail.com>
 */
class Media extends BaseMedia implements SerializableMediaUrl
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = (int) $id;
        return $this;
    }
}