<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20180613160609 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE portal_elements (id INT AUTO_INCREMENT NOT NULL, portal VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, image_url VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, subtitle VARCHAR(255) NOT NULL, button_text VARCHAR(255) NOT NULL, button_link VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX portal_and_locale (portal, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_user_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, email_confirmed TINYINT(1) DEFAULT \'0\' NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', ulule_id VARCHAR(255) DEFAULT NULL, ulule_username VARCHAR(255) DEFAULT NULL, ulule_api_token VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_C560D76192FC23A8 (username_canonical), UNIQUE INDEX UNIQ_C560D761A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_C560D761C05FB297 (confirmation_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE armors (id INT AUTO_INCREMENT NOT NULL, book_id INT DEFAULT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, protection SMALLINT NOT NULL, price SMALLINT NOT NULL, availability VARCHAR(3) NOT NULL, UNIQUE INDEX UNIQ_AFBA56C25E237E06 (name), INDEX IDX_AFBA56C216A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE artifacts (id INT AUTO_INCREMENT NOT NULL, flux_id INT NOT NULL, name VARCHAR(70) NOT NULL, description LONGTEXT DEFAULT NULL, price SMALLINT NOT NULL, consumption SMALLINT NOT NULL, consumption_interval SMALLINT NOT NULL, tank SMALLINT DEFAULT NULL, resistance SMALLINT NOT NULL, vulnerability VARCHAR(255) DEFAULT NULL, handling VARCHAR(20) DEFAULT NULL, damage SMALLINT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, deleted DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_299E46885E237E06 (name), INDEX IDX_299E4688C85926E (flux_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE avantages (id INT AUTO_INCREMENT NOT NULL, book_id INT DEFAULT NULL, name VARCHAR(50) NOT NULL, name_female VARCHAR(50) NOT NULL, xp SMALLINT NOT NULL, description LONGTEXT DEFAULT NULL, augmentation SMALLINT NOT NULL, bonusdisc VARCHAR(10) NOT NULL, is_desv TINYINT(1) NOT NULL, is_combat_art TINYINT(1) NOT NULL, avtg_group SMALLINT DEFAULT 0, UNIQUE INDEX UNIQ_CBC7848D5E237E06 (name), INDEX IDX_CBC7848D16A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE books (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(80) NOT NULL, description LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_4A1B2A925E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters_avantages (character_id INT NOT NULL, advantage_id INT NOT NULL, score INT NOT NULL, INDEX IDX_BB5181061136BE75 (character_id), INDEX IDX_BB5181063864498A (advantage_id), PRIMARY KEY(character_id, advantage_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters_disciplines (character_id INT NOT NULL, discipline_id INT NOT NULL, domain_id INT NOT NULL, score INT NOT NULL, INDEX IDX_50099411136BE75 (character_id), INDEX IDX_5009941A5522701 (discipline_id), INDEX IDX_5009941115F0EE5 (domain_id), PRIMARY KEY(character_id, discipline_id, domain_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters_domains (character_id INT NOT NULL, domain_id INT NOT NULL, score SMALLINT NOT NULL, bonus SMALLINT DEFAULT 0 NOT NULL, malus SMALLINT DEFAULT 0 NOT NULL, INDEX IDX_C4F7C6C61136BE75 (character_id), INDEX IDX_C4F7C6C6115F0EE5 (domain_id), PRIMARY KEY(character_id, domain_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters_flux (flux INT NOT NULL, character_id INT NOT NULL, quantity SMALLINT NOT NULL, INDEX IDX_A1DA630E1136BE75 (character_id), PRIMARY KEY(character_id, flux)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters_setbacks (character_id INT NOT NULL, setback_id INT NOT NULL, is_avoided TINYINT(1) NOT NULL, INDEX IDX_97CD32521136BE75 (character_id), INDEX IDX_97CD3252B42EEDE2 (setback_id), PRIMARY KEY(character_id, setback_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters_ways (character_id INT NOT NULL, way_id INT NOT NULL, score INT NOT NULL, INDEX IDX_7AC056231136BE75 (character_id), INDEX IDX_7AC056238C803113 (way_id), PRIMARY KEY(character_id, way_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters (id INT AUTO_INCREMENT NOT NULL, geo_living_id INT DEFAULT NULL, people_id INT DEFAULT NULL, social_class_id INT DEFAULT NULL, social_class_domain1_id INT DEFAULT NULL, social_class_domain2_id INT DEFAULT NULL, mental_disorder_id INT DEFAULT NULL, job_id INT DEFAULT NULL, birth_place_id INT DEFAULT NULL, trait_flaw_id INT DEFAULT NULL, trait_quality_id INT DEFAULT NULL, user_id INT DEFAULT NULL, game_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, name_slug VARCHAR(255) NOT NULL, player_name VARCHAR(255) NOT NULL, status SMALLINT DEFAULT 0 NOT NULL, sex VARCHAR(1) NOT NULL, description LONGTEXT NOT NULL, story LONGTEXT NOT NULL, facts LONGTEXT NOT NULL, inventory LONGTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\', treasures LONGTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\', orientation VARCHAR(30) NOT NULL, trauma SMALLINT DEFAULT 0 NOT NULL, trauma_permanent SMALLINT DEFAULT 0 NOT NULL, hardening SMALLINT DEFAULT 0 NOT NULL, age SMALLINT NOT NULL, mental_resist SMALLINT NOT NULL, mental_resist_bonus SMALLINT NOT NULL, stamina SMALLINT NOT NULL, stamina_bonus SMALLINT NOT NULL, survival SMALLINT NOT NULL, speed SMALLINT NOT NULL, speed_bonus SMALLINT NOT NULL, defense SMALLINT NOT NULL, defense_bonus SMALLINT NOT NULL, rindath SMALLINT NOT NULL, rindathMax SMALLINT NOT NULL, exaltation SMALLINT NOT NULL, exaltation_max SMALLINT NOT NULL, experience_actual SMALLINT NOT NULL, experience_spent SMALLINT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, deleted DATETIME DEFAULT NULL, daol_ember INT NOT NULL, daol_azure INT NOT NULL, daol_frost INT NOT NULL, health_good SMALLINT NOT NULL, health_okay SMALLINT NOT NULL, health_bad SMALLINT NOT NULL, health_critical SMALLINT NOT NULL, health_agony SMALLINT NOT NULL, max_health_good SMALLINT NOT NULL, max_health_okay SMALLINT NOT NULL, max_health_bad SMALLINT NOT NULL, max_health_critical SMALLINT NOT NULL, max_health_agony SMALLINT NOT NULL, INDEX IDX_3A29410E8B7556B0 (geo_living_id), INDEX IDX_3A29410E3147C936 (people_id), INDEX IDX_3A29410E64319F3C (social_class_id), INDEX IDX_3A29410EC4BE6905 (social_class_domain1_id), INDEX IDX_3A29410ED60BC6EB (social_class_domain2_id), INDEX IDX_3A29410E46CBF851 (mental_disorder_id), INDEX IDX_3A29410EBE04EA9 (job_id), INDEX IDX_3A29410EB4BB6BBC (birth_place_id), INDEX IDX_3A29410E7C43360E (trait_flaw_id), INDEX IDX_3A29410E42FEF757 (trait_quality_id), INDEX IDX_3A29410EA76ED395 (user_id), INDEX IDX_3A29410EE48FD905 (game_id), UNIQUE INDEX idcUnique (name_slug, user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters_armors (characters_id INT NOT NULL, armors_id INT NOT NULL, INDEX IDX_91F54665C70F0E28 (characters_id), INDEX IDX_91F54665333F27F1 (armors_id), PRIMARY KEY(characters_id, armors_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters_artifacts (characters_id INT NOT NULL, artifacts_id INT NOT NULL, INDEX IDX_59084303C70F0E28 (characters_id), INDEX IDX_5908430338F3D9E1 (artifacts_id), PRIMARY KEY(characters_id, artifacts_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters_miracles (characters_id INT NOT NULL, miracles_id INT NOT NULL, INDEX IDX_977340CAC70F0E28 (characters_id), INDEX IDX_977340CA6B117C2B (miracles_id), PRIMARY KEY(characters_id, miracles_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters_ogham (characters_id INT NOT NULL, ogham_id INT NOT NULL, INDEX IDX_53F77947C70F0E28 (characters_id), INDEX IDX_53F779473241FF23 (ogham_id), PRIMARY KEY(characters_id, ogham_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters_weapons (characters_id INT NOT NULL, weapons_id INT NOT NULL, INDEX IDX_1A82C2BAC70F0E28 (characters_id), INDEX IDX_1A82C2BA2EE82581 (weapons_id), PRIMARY KEY(characters_id, weapons_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters_combat_arts (characters_id INT NOT NULL, combat_arts_id INT NOT NULL, INDEX IDX_4423FA34C70F0E28 (characters_id), INDEX IDX_4423FA342E5E3C78 (combat_arts_id), PRIMARY KEY(characters_id, combat_arts_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE characters_status (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE combat_arts (id INT AUTO_INCREMENT NOT NULL, book_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, ranged TINYINT(1) NOT NULL, melee TINYINT(1) NOT NULL, INDEX IDX_EC3E3FAD16A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE disciplines (id INT AUTO_INCREMENT NOT NULL, book_id INT DEFAULT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, rank VARCHAR(40) NOT NULL, UNIQUE INDEX UNIQ_AD1D5CD85E237E06 (name), INDEX IDX_AD1D5CD816A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE disciplines_domains (discipline_id INT NOT NULL, domain_id INT NOT NULL, INDEX IDX_FE41FAE8A5522701 (discipline_id), INDEX IDX_FE41FAE8115F0EE5 (domain_id), PRIMARY KEY(discipline_id, domain_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE disorders (id INT AUTO_INCREMENT NOT NULL, book_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_A14FE96D5E237E06 (name), INDEX IDX_A14FE96D16A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE disorders_ways (disorder_id INT NOT NULL, way_id INT NOT NULL, major TINYINT(1) DEFAULT \'0\' NOT NULL, INDEX IDX_F2628E1787EB36AD (disorder_id), INDEX IDX_F2628E178C803113 (way_id), PRIMARY KEY(disorder_id, way_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE domains (id INT AUTO_INCREMENT NOT NULL, way_id INT DEFAULT NULL, name VARCHAR(70) NOT NULL, description LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_8C7BBF9D5E237E06 (name), INDEX IDX_8C7BBF9D8C803113 (way_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE flux (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(70) NOT NULL, description LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_7252313A5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE games (id INT AUTO_INCREMENT NOT NULL, game_master_id INT NOT NULL, name VARCHAR(140) NOT NULL, summary LONGTEXT DEFAULT NULL, gm_notes LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, deleted DATETIME DEFAULT NULL, INDEX IDX_FF232B31C1151A13 (game_master_id), UNIQUE INDEX idgUnique (name, game_master_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geo_environments (id INT AUTO_INCREMENT NOT NULL, domain_id INT DEFAULT NULL, book_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_18F4720A115F0EE5 (domain_id), INDEX IDX_18F4720A16A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jobs (id INT AUTO_INCREMENT NOT NULL, domain_primary_id INT DEFAULT NULL, book_id INT DEFAULT NULL, name VARCHAR(140) NOT NULL, description LONGTEXT DEFAULT NULL, daily_salary INT DEFAULT 0 NOT NULL, UNIQUE INDEX UNIQ_A8936DC55E237E06 (name), INDEX IDX_A8936DC5B05C1029 (domain_primary_id), INDEX IDX_A8936DC516A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jobs_domains (jobs_id INT NOT NULL, domains_id INT NOT NULL, INDEX IDX_FBB18A2C48704627 (jobs_id), INDEX IDX_FBB18A2C3700F4DC (domains_id), PRIMARY KEY(jobs_id, domains_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE miracles (id INT AUTO_INCREMENT NOT NULL, book_id INT DEFAULT NULL, name VARCHAR(70) NOT NULL, description LONGTEXT DEFAULT NULL, is_major TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_6B8244CF5E237E06 (name), INDEX IDX_6B8244CF16A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ogham (id INT AUTO_INCREMENT NOT NULL, ogham_type_id INT DEFAULT NULL, book_id INT DEFAULT NULL, name VARCHAR(70) NOT NULL, description LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_729005A05E237E06 (name), INDEX IDX_729005A0D7050029 (ogham_type_id), INDEX IDX_729005A016A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ogham_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE peoples (id INT AUTO_INCREMENT NOT NULL, book_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_C92B5C9C16A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE setbacks (id INT AUTO_INCREMENT NOT NULL, book_id INT DEFAULT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, malus VARCHAR(50) NOT NULL, UNIQUE INDEX UNIQ_6B3C36575E237E06 (name), INDEX IDX_6B3C365716A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE social_class (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(25) NOT NULL, description LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_A7DBAD0D5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE social_classes_domains (social_classes_id INT NOT NULL, domains_id INT NOT NULL, INDEX IDX_B915B07A5071E9E6 (social_classes_id), INDEX IDX_B915B07A3700F4DC (domains_id), PRIMARY KEY(social_classes_id, domains_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE traits (id INT AUTO_INCREMENT NOT NULL, way_id INT DEFAULT NULL, book_id INT DEFAULT NULL, name VARCHAR(50) NOT NULL, name_female VARCHAR(50) NOT NULL, is_quality TINYINT(1) NOT NULL, is_major TINYINT(1) NOT NULL, INDEX IDX_E4A0A1668C803113 (way_id), INDEX IDX_E4A0A16616A2B381 (book_id), UNIQUE INDEX idxUnique (name, way_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ways (id INT AUTO_INCREMENT NOT NULL, short_name VARCHAR(3) NOT NULL, name VARCHAR(40) NOT NULL, fault VARCHAR(40) NOT NULL, description LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_A94804173EE4B093 (short_name), UNIQUE INDEX UNIQ_A94804175E237E06 (name), UNIQUE INDEX UNIQ_A94804179FD0DEA3 (fault), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE weapons (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, damage SMALLINT NOT NULL, price SMALLINT NOT NULL, availability VARCHAR(5) NOT NULL, melee TINYINT(1) NOT NULL, weapon_range SMALLINT NOT NULL, UNIQUE INDEX UNIQ_520EBBE15E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, percentage NUMERIC(8, 6) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_5387574A5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events_foes (events_id INT NOT NULL, foes_id INT NOT NULL, INDEX IDX_C15440C09D6A1065 (events_id), INDEX IDX_C15440C03DF0F043 (foes_id), PRIMARY KEY(events_id, foes_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events_npcs (events_id INT NOT NULL, npcs_id INT NOT NULL, INDEX IDX_45C02BE49D6A1065 (events_id), INDEX IDX_45C02BE473DFFBCA (npcs_id), PRIMARY KEY(events_id, npcs_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events_weather (events_id INT NOT NULL, weather_id INT NOT NULL, INDEX IDX_1AB1AA749D6A1065 (events_id), INDEX IDX_1AB1AA748CE675E (weather_id), PRIMARY KEY(events_id, weather_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events_markers (events_id INT NOT NULL, markers_id INT NOT NULL, INDEX IDX_17E8A62A9D6A1065 (events_id), INDEX IDX_17E8A62AD0EEC2B5 (markers_id), PRIMARY KEY(events_id, markers_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events_markers_types (events_id INT NOT NULL, markers_types_id INT NOT NULL, INDEX IDX_80FAF5E89D6A1065 (events_id), INDEX IDX_80FAF5E888F4A4BD (markers_types_id), PRIMARY KEY(events_id, markers_types_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events_resources (events_id INT NOT NULL, resources_id INT NOT NULL, INDEX IDX_76928E8C9D6A1065 (events_id), INDEX IDX_76928E8CACFC5BFF (resources_id), PRIMARY KEY(events_id, resources_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events_routes (events_id INT NOT NULL, routes_id INT NOT NULL, INDEX IDX_E068FB869D6A1065 (events_id), INDEX IDX_E068FB86AE2C16DC (routes_id), PRIMARY KEY(events_id, routes_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events_routes_types (events_id INT NOT NULL, routes_types_id INT NOT NULL, INDEX IDX_7375FC699D6A1065 (events_id), INDEX IDX_7375FC6959514061 (routes_types_id), PRIMARY KEY(events_id, routes_types_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events_zones_types (events_id INT NOT NULL, zones_types_id INT NOT NULL, INDEX IDX_7E6C54359D6A1065 (events_id), INDEX IDX_7E6C54357B85C61C (zones_types_id), PRIMARY KEY(events_id, zones_types_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events_zones (events_id INT NOT NULL, zones_id INT NOT NULL, INDEX IDX_3576794E9D6A1065 (events_id), INDEX IDX_3576794EA6EAEB7A (zones_id), PRIMARY KEY(events_id, zones_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps_factions (id INT AUTO_INCREMENT NOT NULL, book_id INT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_354BB9A75E237E06 (name), INDEX IDX_354BB9A716A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps_foes (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_B9BE805E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, name_slug VARCHAR(255) NOT NULL, image VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, max_zoom SMALLINT DEFAULT 1 NOT NULL, start_zoom SMALLINT DEFAULT 1 NOT NULL, start_x SMALLINT DEFAULT 1 NOT NULL, start_y SMALLINT DEFAULT 1 NOT NULL, bounds VARCHAR(255) DEFAULT \'[]\' NOT NULL, coordinates_ratio SMALLINT DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_472E08A55E237E06 (name), UNIQUE INDEX UNIQ_472E08A5DF2B4115 (name_slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps_markers (id INT AUTO_INCREMENT NOT NULL, faction_id INT DEFAULT NULL, map_id INT NOT NULL, marker_type_id INT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, altitude VARCHAR(255) DEFAULT \'0\' NOT NULL, latitude VARCHAR(255) DEFAULT \'0\' NOT NULL, longitude VARCHAR(255) DEFAULT \'0\' NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_33F679DD5E237E06 (name), INDEX IDX_33F679DD4448F8DA (faction_id), INDEX IDX_33F679DD53C55F64 (map_id), INDEX IDX_33F679DDBFC01D99 (marker_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps_markers_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, icon VARCHAR(255) NOT NULL, icon_width INT NOT NULL, icon_height INT NOT NULL, icon_center_x INT DEFAULT NULL, icon_center_y INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_C4AFA515E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps_npcs (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_842DD5A45E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps_resources (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_3B0312AD5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE resources_routes (resources_id INT NOT NULL, routes_id INT NOT NULL, INDEX IDX_389FB5C1ACFC5BFF (resources_id), INDEX IDX_389FB5C1AE2C16DC (routes_id), PRIMARY KEY(resources_id, routes_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE resources_routes_types (resources_id INT NOT NULL, routes_types_id INT NOT NULL, INDEX IDX_1EC06A03ACFC5BFF (resources_id), INDEX IDX_1EC06A0359514061 (routes_types_id), PRIMARY KEY(resources_id, routes_types_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE resources_zones_types (resources_id INT NOT NULL, zones_types_id INT NOT NULL, INDEX IDX_161ED520ACFC5BFF (resources_id), INDEX IDX_161ED5207B85C61C (zones_types_id), PRIMARY KEY(resources_id, zones_types_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps_routes (id INT AUTO_INCREMENT NOT NULL, marker_start_id INT DEFAULT NULL, marker_end_id INT DEFAULT NULL, map_id INT NOT NULL, faction_id INT DEFAULT NULL, route_type_id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, coordinates LONGTEXT NOT NULL, distance DOUBLE PRECISION DEFAULT \'0\' NOT NULL, forced_distance DOUBLE PRECISION DEFAULT NULL, guarded TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_4A14AA7582929C14 (marker_start_id), INDEX IDX_4A14AA75476289B (marker_end_id), INDEX IDX_4A14AA7553C55F64 (map_id), INDEX IDX_4A14AA754448F8DA (faction_id), INDEX IDX_4A14AA753D1FD10B (route_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps_routes_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, color VARCHAR(75) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_1006B6375E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps_routes_transports (id INT AUTO_INCREMENT NOT NULL, route_type_id INT NOT NULL, transport_type_id INT NOT NULL, percentage NUMERIC(9, 6) DEFAULT \'100\' NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_DC8B306C3D1FD10B (route_type_id), INDEX IDX_DC8B306C519B4C62 (transport_type_id), UNIQUE INDEX unique_route_transport (route_type_id, transport_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps_transports_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, speed NUMERIC(8, 4) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_937FC7725E237E06 (name), UNIQUE INDEX UNIQ_937FC772989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps_weather (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_3EAF75835E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps_zones (id INT AUTO_INCREMENT NOT NULL, map_id INT NOT NULL, faction_id INT DEFAULT NULL, zone_type_id INT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, coordinates LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_436BD5205E237E06 (name), INDEX IDX_436BD52053C55F64 (map_id), INDEX IDX_436BD5204448F8DA (faction_id), INDEX IDX_436BD5207B788FAB (zone_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maps_zones_types (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, color VARCHAR(75) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_B4AD3285E237E06 (name), INDEX IDX_B4AD328727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE armors ADD CONSTRAINT FK_AFBA56C216A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE artifacts ADD CONSTRAINT FK_299E4688C85926E FOREIGN KEY (flux_id) REFERENCES flux (id)');
        $this->addSql('ALTER TABLE avantages ADD CONSTRAINT FK_CBC7848D16A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE characters_avantages ADD CONSTRAINT FK_BB5181061136BE75 FOREIGN KEY (character_id) REFERENCES characters (id)');
        $this->addSql('ALTER TABLE characters_avantages ADD CONSTRAINT FK_BB5181063864498A FOREIGN KEY (advantage_id) REFERENCES avantages (id)');
        $this->addSql('ALTER TABLE characters_disciplines ADD CONSTRAINT FK_50099411136BE75 FOREIGN KEY (character_id) REFERENCES characters (id)');
        $this->addSql('ALTER TABLE characters_disciplines ADD CONSTRAINT FK_5009941A5522701 FOREIGN KEY (discipline_id) REFERENCES disciplines (id)');
        $this->addSql('ALTER TABLE characters_disciplines ADD CONSTRAINT FK_5009941115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE characters_domains ADD CONSTRAINT FK_C4F7C6C61136BE75 FOREIGN KEY (character_id) REFERENCES characters (id)');
        $this->addSql('ALTER TABLE characters_domains ADD CONSTRAINT FK_C4F7C6C6115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE characters_flux ADD CONSTRAINT FK_A1DA630E1136BE75 FOREIGN KEY (character_id) REFERENCES characters (id)');
        $this->addSql('ALTER TABLE characters_setbacks ADD CONSTRAINT FK_97CD32521136BE75 FOREIGN KEY (character_id) REFERENCES characters (id)');
        $this->addSql('ALTER TABLE characters_setbacks ADD CONSTRAINT FK_97CD3252B42EEDE2 FOREIGN KEY (setback_id) REFERENCES setbacks (id)');
        $this->addSql('ALTER TABLE characters_ways ADD CONSTRAINT FK_7AC056231136BE75 FOREIGN KEY (character_id) REFERENCES characters (id)');
        $this->addSql('ALTER TABLE characters_ways ADD CONSTRAINT FK_7AC056238C803113 FOREIGN KEY (way_id) REFERENCES ways (id)');
        $this->addSql('ALTER TABLE characters ADD CONSTRAINT FK_3A29410E8B7556B0 FOREIGN KEY (geo_living_id) REFERENCES geo_environments (id)');
        $this->addSql('ALTER TABLE characters ADD CONSTRAINT FK_3A29410E3147C936 FOREIGN KEY (people_id) REFERENCES peoples (id)');
        $this->addSql('ALTER TABLE characters ADD CONSTRAINT FK_3A29410E64319F3C FOREIGN KEY (social_class_id) REFERENCES social_class (id)');
        $this->addSql('ALTER TABLE characters ADD CONSTRAINT FK_3A29410EC4BE6905 FOREIGN KEY (social_class_domain1_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE characters ADD CONSTRAINT FK_3A29410ED60BC6EB FOREIGN KEY (social_class_domain2_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE characters ADD CONSTRAINT FK_3A29410E46CBF851 FOREIGN KEY (mental_disorder_id) REFERENCES disorders (id)');
        $this->addSql('ALTER TABLE characters ADD CONSTRAINT FK_3A29410EBE04EA9 FOREIGN KEY (job_id) REFERENCES jobs (id)');
        $this->addSql('ALTER TABLE characters ADD CONSTRAINT FK_3A29410EB4BB6BBC FOREIGN KEY (birth_place_id) REFERENCES maps_zones (id)');
        $this->addSql('ALTER TABLE characters ADD CONSTRAINT FK_3A29410E7C43360E FOREIGN KEY (trait_flaw_id) REFERENCES traits (id)');
        $this->addSql('ALTER TABLE characters ADD CONSTRAINT FK_3A29410E42FEF757 FOREIGN KEY (trait_quality_id) REFERENCES traits (id)');
        $this->addSql('ALTER TABLE characters ADD CONSTRAINT FK_3A29410EA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE characters ADD CONSTRAINT FK_3A29410EE48FD905 FOREIGN KEY (game_id) REFERENCES games (id)');
        $this->addSql('ALTER TABLE characters_armors ADD CONSTRAINT FK_91F54665C70F0E28 FOREIGN KEY (characters_id) REFERENCES characters (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE characters_armors ADD CONSTRAINT FK_91F54665333F27F1 FOREIGN KEY (armors_id) REFERENCES armors (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE characters_artifacts ADD CONSTRAINT FK_59084303C70F0E28 FOREIGN KEY (characters_id) REFERENCES characters (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE characters_artifacts ADD CONSTRAINT FK_5908430338F3D9E1 FOREIGN KEY (artifacts_id) REFERENCES artifacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE characters_miracles ADD CONSTRAINT FK_977340CAC70F0E28 FOREIGN KEY (characters_id) REFERENCES characters (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE characters_miracles ADD CONSTRAINT FK_977340CA6B117C2B FOREIGN KEY (miracles_id) REFERENCES miracles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE characters_ogham ADD CONSTRAINT FK_53F77947C70F0E28 FOREIGN KEY (characters_id) REFERENCES characters (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE characters_ogham ADD CONSTRAINT FK_53F779473241FF23 FOREIGN KEY (ogham_id) REFERENCES ogham (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE characters_weapons ADD CONSTRAINT FK_1A82C2BAC70F0E28 FOREIGN KEY (characters_id) REFERENCES characters (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE characters_weapons ADD CONSTRAINT FK_1A82C2BA2EE82581 FOREIGN KEY (weapons_id) REFERENCES weapons (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE characters_combat_arts ADD CONSTRAINT FK_4423FA34C70F0E28 FOREIGN KEY (characters_id) REFERENCES characters (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE characters_combat_arts ADD CONSTRAINT FK_4423FA342E5E3C78 FOREIGN KEY (combat_arts_id) REFERENCES combat_arts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE combat_arts ADD CONSTRAINT FK_EC3E3FAD16A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE disciplines ADD CONSTRAINT FK_AD1D5CD816A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE disciplines_domains ADD CONSTRAINT FK_FE41FAE8A5522701 FOREIGN KEY (discipline_id) REFERENCES disciplines (id)');
        $this->addSql('ALTER TABLE disciplines_domains ADD CONSTRAINT FK_FE41FAE8115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE disorders ADD CONSTRAINT FK_A14FE96D16A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE disorders_ways ADD CONSTRAINT FK_F2628E1787EB36AD FOREIGN KEY (disorder_id) REFERENCES disorders (id)');
        $this->addSql('ALTER TABLE disorders_ways ADD CONSTRAINT FK_F2628E178C803113 FOREIGN KEY (way_id) REFERENCES ways (id)');
        $this->addSql('ALTER TABLE domains ADD CONSTRAINT FK_8C7BBF9D8C803113 FOREIGN KEY (way_id) REFERENCES ways (id)');
        $this->addSql('ALTER TABLE games ADD CONSTRAINT FK_FF232B31C1151A13 FOREIGN KEY (game_master_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE geo_environments ADD CONSTRAINT FK_18F4720A115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE geo_environments ADD CONSTRAINT FK_18F4720A16A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE jobs ADD CONSTRAINT FK_A8936DC5B05C1029 FOREIGN KEY (domain_primary_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE jobs ADD CONSTRAINT FK_A8936DC516A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE jobs_domains ADD CONSTRAINT FK_FBB18A2C48704627 FOREIGN KEY (jobs_id) REFERENCES jobs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jobs_domains ADD CONSTRAINT FK_FBB18A2C3700F4DC FOREIGN KEY (domains_id) REFERENCES domains (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE miracles ADD CONSTRAINT FK_6B8244CF16A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE ogham ADD CONSTRAINT FK_729005A0D7050029 FOREIGN KEY (ogham_type_id) REFERENCES ogham_types (id)');
        $this->addSql('ALTER TABLE ogham ADD CONSTRAINT FK_729005A016A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE peoples ADD CONSTRAINT FK_C92B5C9C16A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE setbacks ADD CONSTRAINT FK_6B3C365716A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE social_classes_domains ADD CONSTRAINT FK_B915B07A5071E9E6 FOREIGN KEY (social_classes_id) REFERENCES social_class (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE social_classes_domains ADD CONSTRAINT FK_B915B07A3700F4DC FOREIGN KEY (domains_id) REFERENCES domains (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE traits ADD CONSTRAINT FK_E4A0A1668C803113 FOREIGN KEY (way_id) REFERENCES ways (id)');
        $this->addSql('ALTER TABLE traits ADD CONSTRAINT FK_E4A0A16616A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE events_foes ADD CONSTRAINT FK_C15440C09D6A1065 FOREIGN KEY (events_id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_foes ADD CONSTRAINT FK_C15440C03DF0F043 FOREIGN KEY (foes_id) REFERENCES maps_foes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_npcs ADD CONSTRAINT FK_45C02BE49D6A1065 FOREIGN KEY (events_id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_npcs ADD CONSTRAINT FK_45C02BE473DFFBCA FOREIGN KEY (npcs_id) REFERENCES maps_npcs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_weather ADD CONSTRAINT FK_1AB1AA749D6A1065 FOREIGN KEY (events_id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_weather ADD CONSTRAINT FK_1AB1AA748CE675E FOREIGN KEY (weather_id) REFERENCES maps_weather (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_markers ADD CONSTRAINT FK_17E8A62A9D6A1065 FOREIGN KEY (events_id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_markers ADD CONSTRAINT FK_17E8A62AD0EEC2B5 FOREIGN KEY (markers_id) REFERENCES maps_markers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_markers_types ADD CONSTRAINT FK_80FAF5E89D6A1065 FOREIGN KEY (events_id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_markers_types ADD CONSTRAINT FK_80FAF5E888F4A4BD FOREIGN KEY (markers_types_id) REFERENCES maps_markers_types (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_resources ADD CONSTRAINT FK_76928E8C9D6A1065 FOREIGN KEY (events_id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_resources ADD CONSTRAINT FK_76928E8CACFC5BFF FOREIGN KEY (resources_id) REFERENCES maps_resources (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_routes ADD CONSTRAINT FK_E068FB869D6A1065 FOREIGN KEY (events_id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_routes ADD CONSTRAINT FK_E068FB86AE2C16DC FOREIGN KEY (routes_id) REFERENCES maps_routes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_routes_types ADD CONSTRAINT FK_7375FC699D6A1065 FOREIGN KEY (events_id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_routes_types ADD CONSTRAINT FK_7375FC6959514061 FOREIGN KEY (routes_types_id) REFERENCES maps_routes_types (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_zones_types ADD CONSTRAINT FK_7E6C54359D6A1065 FOREIGN KEY (events_id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_zones_types ADD CONSTRAINT FK_7E6C54357B85C61C FOREIGN KEY (zones_types_id) REFERENCES maps_zones_types (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_zones ADD CONSTRAINT FK_3576794E9D6A1065 FOREIGN KEY (events_id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events_zones ADD CONSTRAINT FK_3576794EA6EAEB7A FOREIGN KEY (zones_id) REFERENCES maps_zones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE maps_factions ADD CONSTRAINT FK_354BB9A716A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE maps_markers ADD CONSTRAINT FK_33F679DD4448F8DA FOREIGN KEY (faction_id) REFERENCES maps_factions (id)');
        $this->addSql('ALTER TABLE maps_markers ADD CONSTRAINT FK_33F679DD53C55F64 FOREIGN KEY (map_id) REFERENCES maps (id)');
        $this->addSql('ALTER TABLE maps_markers ADD CONSTRAINT FK_33F679DDBFC01D99 FOREIGN KEY (marker_type_id) REFERENCES maps_markers_types (id)');
        $this->addSql('ALTER TABLE resources_routes ADD CONSTRAINT FK_389FB5C1ACFC5BFF FOREIGN KEY (resources_id) REFERENCES maps_resources (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resources_routes ADD CONSTRAINT FK_389FB5C1AE2C16DC FOREIGN KEY (routes_id) REFERENCES maps_routes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resources_routes_types ADD CONSTRAINT FK_1EC06A03ACFC5BFF FOREIGN KEY (resources_id) REFERENCES maps_resources (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resources_routes_types ADD CONSTRAINT FK_1EC06A0359514061 FOREIGN KEY (routes_types_id) REFERENCES maps_routes_types (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resources_zones_types ADD CONSTRAINT FK_161ED520ACFC5BFF FOREIGN KEY (resources_id) REFERENCES maps_resources (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resources_zones_types ADD CONSTRAINT FK_161ED5207B85C61C FOREIGN KEY (zones_types_id) REFERENCES maps_zones_types (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE maps_routes ADD CONSTRAINT FK_4A14AA7582929C14 FOREIGN KEY (marker_start_id) REFERENCES maps_markers (id)');
        $this->addSql('ALTER TABLE maps_routes ADD CONSTRAINT FK_4A14AA75476289B FOREIGN KEY (marker_end_id) REFERENCES maps_markers (id)');
        $this->addSql('ALTER TABLE maps_routes ADD CONSTRAINT FK_4A14AA7553C55F64 FOREIGN KEY (map_id) REFERENCES maps (id)');
        $this->addSql('ALTER TABLE maps_routes ADD CONSTRAINT FK_4A14AA754448F8DA FOREIGN KEY (faction_id) REFERENCES maps_factions (id)');
        $this->addSql('ALTER TABLE maps_routes ADD CONSTRAINT FK_4A14AA753D1FD10B FOREIGN KEY (route_type_id) REFERENCES maps_routes_types (id)');
        $this->addSql('ALTER TABLE maps_routes_transports ADD CONSTRAINT FK_DC8B306C3D1FD10B FOREIGN KEY (route_type_id) REFERENCES maps_routes_types (id)');
        $this->addSql('ALTER TABLE maps_routes_transports ADD CONSTRAINT FK_DC8B306C519B4C62 FOREIGN KEY (transport_type_id) REFERENCES maps_transports_types (id)');
        $this->addSql('ALTER TABLE maps_zones ADD CONSTRAINT FK_436BD52053C55F64 FOREIGN KEY (map_id) REFERENCES maps (id)');
        $this->addSql('ALTER TABLE maps_zones ADD CONSTRAINT FK_436BD5204448F8DA FOREIGN KEY (faction_id) REFERENCES maps_factions (id)');
        $this->addSql('ALTER TABLE maps_zones ADD CONSTRAINT FK_436BD5207B788FAB FOREIGN KEY (zone_type_id) REFERENCES maps_zones_types (id)');
        $this->addSql('ALTER TABLE maps_zones_types ADD CONSTRAINT FK_B4AD328727ACA70 FOREIGN KEY (parent_id) REFERENCES maps_zones_types (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
    }
}
