module.exports = [
    // Copy script
    "web/fonts/roboto/Roboto-Bold.woff",
    "web/fonts/roboto/Roboto-Bold.woff2",
    "web/fonts/roboto/Roboto-Light.woff",
    "web/fonts/roboto/Roboto-Light.woff2",
    "web/fonts/roboto/Roboto-Medium.woff",
    "web/fonts/roboto/Roboto-Medium.woff2",
    "web/fonts/roboto/Roboto-Regular.woff",
    "web/fonts/roboto/Roboto-Regular.woff2",
    "web/fonts/roboto/Roboto-Thin.woff",
    "web/fonts/roboto/Roboto-Thin.woff2",
    "web/fonts/FontAwesome.otf",
    "web/fonts/fontawesome-webfont.eot",
    "web/fonts/fontawesome-webfont.svg",
    "web/fonts/fontawesome-webfont.ttf",
    "web/fonts/fontawesome-webfont.woff",
    "web/fonts/fontawesome-webfont.woff2",
    "web/fonts/glyphicons-halflings-regular.eot",
    "web/fonts/glyphicons-halflings-regular.svg",
    "web/fonts/glyphicons-halflings-regular.ttf",
    "web/fonts/glyphicons-halflings-regular.woff",
    "web/fonts/glyphicons-halflings-regular.woff2",
    "web/images/layers-2x.png",
    "web/images/layers.png",
    "web/images/marker-icon-2x.png",
    "web/images/marker-icon.png",
    "web/images/marker-shadow.png",

    // Image script
    "web/img/agate/Agate_7th_Sea.jpg",
    "web/img/agate/Esteren_Crew.jpg",
    "web/img/agate/esteren_dearg_front.jpg",
    "web/img/agate/logo_agate_studio_big.png",
    "web/img/agate/logo_agate_studio_stone.png",
    "web/img/agate/logo_agate_studio_words.png",
    "web/img/agate/Portal_7e_Mer_Logo.png",
    "web/img/agate/Portal_Dragons_logo.jpg",
    "web/img/agate/Portal_Esteren_logo.png",
    "web/img/agate/Portal_logo_agate_studio_stone.png",
    "web/img/agate/Portal_Vampire_Requiem_Logo.png",
    "web/img/agate/Portal_Vermine_background.jpg",
    "web/img/agate/Portal_Vermine_logo.jpg",
    "web/img/agate/team/akae.jpg",
    "web/img/agate/team/asami.jpg",
    "web/img/agate/team/ben.jpg",
    "web/img/agate/team/chane.jpg",
    "web/img/agate/team/chris.jpg",
    "web/img/agate/team/clarisse_may.jpg",
    "web/img/agate/team/clovis.jpg",
    "web/img/agate/team/david_camus.jpg",
    "web/img/agate/team/dominique_atlan.jpg",
    "web/img/agate/team/dref.jpg",
    "web/img/agate/team/francois_rousselot.jpg",
    "web/img/agate/team/gawain.jpg",
    "web/img/agate/team/ginl.jpg",
    "web/img/agate/team/iris.jpg",
    "web/img/agate/team/julien_blondel.jpg",
    "web/img/agate/team/lison.jpg",
    "web/img/agate/team/nel.jpg",
    "web/img/agate/team/nico_jamme.jpg",
    "web/img/agate/team/pierstoval.jpg",
    "web/img/agate/team/sebastien_chedal.jpg",
    "web/img/agate/team/valentin.jpg",
    "web/img/background-image.jpg",
    "web/img/d10.svg",
    "web/img/Esteren_Arven_marche.jpg",
    "web/img/Esteren_logo_400.png",
    "web/img/Esteren_monolith.jpg",
    "web/img/Esteren_monolith_o.jpg",
    "web/img/Esteren_stones.jpg",
    "web/img/favicon-114.png",
    "web/img/favicon-144.png",
    "web/img/favicon-57.png",
    "web/img/favicon-72.png",
    "web/img/favicon.png",
    "web/img/generator/search.png",
    "web/img/markerstypes/icones.png",
    "web/img/markerstypes/invisible.png",
    "web/img/markerstypes/pastille-beige-light.png",
    "web/img/markerstypes/pastille-beige.png",
    "web/img/markerstypes/pastille-blue-dark.png",
    "web/img/markerstypes/pastille-blue.png",
    "web/img/markerstypes/pastille-gray-light.png",
    "web/img/markerstypes/pastille-gray.png",
    "web/img/markerstypes/pastille-green-dark.png",
    "web/img/markerstypes/pastille-green.png",
    "web/img/markerstypes/pastille-red-dark.png",
    "web/img/markerstypes/pastille-red-darker.png",

    // LESS script
    "web/css/fa.css",
    "web/css/global.css",
    "web/css/maps_lib.css",
    "web/css/admin.css",
    "web/css/generator.css",
    "web/css/character_details.css",

    // SASS script
    "web/css/global_mat.css",
    "web/css/agate.css",
    "web/css/white_layout.css",

    // CSS script
    "web/css/initializer.css",

    // JS script
    "web/js/jquery.js",
    "web/js/global.js",
    "web/js/global_mat.js",
    "web/js/maps_lib.js",
    "web/js/generator.js",
    "web/js/step_03_birthplace.js",
    "web/js/step_11_advantages.js",
    "web/js/step_13_primary_domains.js",
    "web/js/step_14_use_domain_bonuses.js",
    "web/js/step_15_domains_spend_exp.js",
    "web/js/step_16_disciplines.js",
    "web/js/step_17_combat_arts.js",
    "web/js/step_18_equipment.js",
];
